name: Cypress-e2e

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Cypress
        run: npm install cypress
      - name: cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run
          browser: chrome
